format = """
[â•­â”€](bold green) $os\
$conda\
$directory\
${custom.git_branch}\
${custom.git_status}\
${custom.jj}\
$python\
$rust\
$lua\
$fill\
$cmd_duration\
$time\
$line_break\
[â•°â”€](bold green)$character
"""

add_newline = true
palette = "catppuccin_latte"
command_timeout = 2000

[os]
disabled = false
style = 'green'

[os.symbols]
Windows = "î˜ª "
Ubuntu = "ó°•ˆ "
Arch = "ó°£‡ "

[conda]
symbol = "îœ• "
format = "[$symbol$environment]($style) "
style = 'bold green'

[directory]
style = 'bold sky'
format = '[$path ]($style)'
truncation_length = 5
truncation_symbol = 'â€¦/'
truncate_to_repo = false

[directory.substitutions]
'Documents' = 'ó°ˆ™'
'Downloads' = 'ï€™ '
'Music' = 'ï€ '
'Pictures' = 'ï€¾ '

[git_branch]
disabled = true
symbol = 'ï˜ '
style = 'teal'

[custom.git_branch]
description = "Only show git_branch if we're not in a jj repo"
when = "! jj --ignore-working-copy root"
command = "starship module git_branch"

[git_status]
disabled = true
format = '([$all_status$ahead_behind]($style) )'
style = 'red'

[custom.git_status]
description = "Only show git_status if we're not in a jj repo"
when = "! jj --ignore-working-copy root"
command = "starship module git_status"

[custom.jj]
description = "The current jj status"
when = "jj --ignore-working-copy root"
symbol = "ï˜ "
command = '''
jj log --revisions @ --no-graph --ignore-working-copy --color always --limit 1 --template '
  separate(" ",
    change_id.shortest(4),
    bookmarks,
    concat(
      if(conflict, "ğŸ’¥"),
      if(divergent, "ğŸš§"),
      if(hidden, "ğŸ‘»"),
      if(immutable, "ğŸ”’"),
    ),
    raw_escape_sequence("\x1b[1;32m") ++ if(
      empty,
      raw_escape_sequence("\x1b[1;32m") ++ "ó°±’" ++ raw_escape_sequence("\x1b[0m"),
      raw_escape_sequence("\x1b[1;33m") ++ "ó°­" ++ raw_escape_sequence("\x1b[0m")
    ),
    raw_escape_sequence(
      if(description.first_line(), "\x1b[1;33m", "\x1b[1;32m")
    )
    ++ coalesce(
      truncate_end(29, description.first_line(), "â€¦"),
      "ó°„± "
    )
    ++ raw_escape_sequence("\x1b[0m")
  )
'
'''

[python]
symbol = 'îˆµ '
style = 'lavender'

[rust]
symbol = 'îš‹ '
style = 'maroon'

[lua]
symbol = 'î˜  '
style = 'blue'

[fill]
symbol = ' '

[cmd_duration]
format = 'took [$duration](overlay0) '
style = 'overlay0'
min_time = 60000

[time]
disabled = false
time_format = "%T"
style = "overlay0"
format = ' ïº [$time ]($style)'


[character]
success_symbol = '[](bold green)'
error_symbol = '[!](bold red)'

[palettes.catppuccin_latte]
rosewater = "#dc8a78"
flamingo = "#dd7878"
pink = "#ea76cb"
mauve = "#8839ef"
red = "#d20f39"
maroon = "#e64553"
peach = "#fe640b"
yellow = "#df8e1d"
green = "#40a02b"
teal = "#179299"
sky = "#04a5e5"
sapphire = "#209fb5"
blue = "#1e66f5"
lavender = "#7287fd"
text = "#4c4f69"
subtext1 = "#5c5f77"
subtext0 = "#6c6f85"
overlay2 = "#7c7f93"
overlay1 = "#8c8fa1"
overlay0 = "#9ca0b0"
surface2 = "#acb0be"
surface1 = "#bcc0cc"
surface0 = "#ccd0da"
base = "#eff1f5"
mantle = "#e6e9ef"
crust = "#dce0e8"
