#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Ricardo"
email = "ricardoryn1317@gmail.com"

[ui]
default-command = "log"
editor = "nvim"
pager = ["delta", "--pager", "less -FRX"]
diff-formatter = ":git"
diff-editor = ["nvim", "-c", "DiffEditor $left $right $output"]
diff-instructions = false
merge-editor = "vimdiff"

[git]
private-commits = '''description(glob:'WIP:*')'''

[lazyjj]
highlight-color = "#cccccc"
diff-tool = "delta"

[template-aliases]
"format_short_signature(signature)" = "signature.name()"
"format_timestamp(timestamp)" = "timestamp.ago()"

[aliases]
l = ["log", "-r", "::", "-n", "7"]

[merge-tools.vimdiff]
program = "nvim"
merge-args = ["-f", "-d", "$output", "-M",
    "$left", "$base", "$right",
    "-c", "wincmd J", "-c", "set modifiable",
    "-c", "set write"]
merge-tool-edits-conflict-markers = true
